"""empty message

Revision ID: 239233146395
Revises: 6553ea018a1b
Create Date: 2023-03-27 07:25:22.360244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239233146395'
down_revision = '6553ea018a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
