 cliente1 = Cliente(nombre='Jafet',direccion='Arecas')
     #    cliente2 = Cliente(nombre='Jorge',direccion='Tampico')
     #    clientesinserts = ClienteDAO.insertar(cliente1)
     #    clientesinserts = ClienteDAO.insertar(cliente2)
     #    log.debug(f'clientes insertados: {clientesinserts}')