"""empty message

Revision ID: a7a4f7eaf41d
Revises: 
Create Date: 2023-05-29 18:25:44.874252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a4f7eaf41d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comentarios_Calificaciones',
    sa.Column('idComentario_Calif', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_cliente', sa.String(length=255), nullable=False),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idComentario_Calif')
    )
    op.create_table('Menus',
    sa.Column('idMenu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idMenu'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Pedidos',
    sa.Column('idPedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreCliente', sa.String(length=255), nullable=False),
    sa.Column('direccionCliente', sa.String(length=255), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estatus', sa.String(length=60), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('idPedido'),
    sa.UniqueConstraint('nombreCliente')
    )
    op.create_table('Sucursales',
    sa.Column('idSucursal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('correo_electronico', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('idSucursal'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Empleados',
    sa.Column('idEmpleado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('puesto', sa.String(length=255), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idSucursal'], ['Sucursales.idSucursal'], ),
    sa.PrimaryKeyConstraint('idEmpleado'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('HistorialPedidos',
    sa.Column('idHistorial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido', sa.String(length=255), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estatus', sa.String(length=60), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=False),
    sa.Column('idEmpleado', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idEmpleado'], ['Empleados.idEmpleado'], ),
    sa.PrimaryKeyConstraint('idHistorial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HistorialPedidos')
    op.drop_table('Empleados')
    op.drop_table('Sucursales')
    op.drop_table('Pedidos')
    op.drop_table('Menus')
    op.drop_table('Comentarios_Calificaciones')
    # ### end Alembic commands ###
