# Generated by Django 4.2 on 2023-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrejuego', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('compañia', models.CharField(max_length=255)),
            ],
        ),
    ]
